/* USERDTO 테이블 생성 */
DROP TABLE USERDTO
CASCADE CONSTRAINT;

DROP SEQUENCE USER_SEQ;

CREATE TABLE USERDTO(
	USER_SEQ NUMBER(8),
	ID	VARCHAR2(50) PRIMARY KEY,
	PASSWORD VARCHAR2(50) NOT NULL,
	NAME	VARCHAR2(50) NOT NULL,
	BIRTH	VARCHAR2(50)	NOT NULL,
	EMAIL	VARCHAR2(50)	NOT NULL,
	PIC	VARCHAR2(1000),
	DEL	NUMBER(1)	NOT NULL	
)

CREATE SEQUENCE USER_SEQ
START WITH 1
INCREMENT BY 1;

/* 일정관리 테이블 생성 */

DROP TABLE SCHEDULE
CASCADE CONSTRAINT;

DROP SEQUENCE SHECDELE_SEQ;

CREATE TABLE SCHEDULE(
	SHECDELE_SEQ	NUMBER(8),
	ID	VARCHAR2(50),
	TITLE	VARCHAR2(50) NOT NULL,
	STARTDATE	DATE	NOT NULL,
	ENDDATE	DATE	NOT NULL,
	CATEGORY	VARCHAR2(50),
	CONTENT	VARCHAR2(2000)	NOT NULL,
	IMPORTANT	NUMBER(1)	NOT NULL,
	DEL	NUMBER(1)	NOT NULL
)

CREATE SEQUENCE SHECDELE_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE SCHEDULE
	ADD CONSTRAINT FK_SCHEDULE_ID FOREIGN KEY(ID)
	REFERENCES USERDTO(ID);

/* 가계부 테이블 만들기 */

DROP TABLE CASHBOOK
CASCADE CONSTRAINT

DROP SEQUENCE CASHBOOK_SEQ

CREATE TABLE CASHBOOK(
	CASHBOOK_SEQ	NUMBER(8),
	ID	VARCHAR2(50),
	TITLE	VARCHAR2(50)	NOT NULL,
	CASHDATE	DATE	NOT NULL,
	IOCASH	NUMBER(1)	NOT NULL,
	CATEGORY	NUMBER(2),
	CONTENT	VARCHAR2(2000)	NOT NULL,
	DEL	NUMBER(1)	NOT NULL
)

CREATE SEQUENCE CASHBOOK_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE CASHBOOK
	ADD CONSTRAINT FK_CASHBOOK_ID FOREIGN KEY(ID)
	REFERENCES USERDTO(ID);
